---
- name: Monitorizar URLs y comprobar textos especificos
  hosts: localhost
  tasks:
    - name: Hacer una solicitud HTTP a la primera URL Portal en 145
      uri:
        url: http://172.16.200.145:8080/rrhh/ingreso
        return_content: yes
      register: response_portalRHP01

    - name: Comprobar si el texto 'Empresa222' esta presente en la primera URL Portal en 145
      set_fact:
        should_act_on_rhp01: "{{ 'Empresa222' not in response_portalRHP01.content }}"

    - name: Hacer una solicitud HTTP a la primera URL RedNat en 145
      uri:
        url: http://172.16.200.145:8080/grh-nat-web/login.seam
        return_content: yes
      register: response_rednatRHP01

    - name: Comprobar si el texto 'Ingrese2222' esta presente en la primera URL RedNat en 145
      set_fact:
        should_act_on_rhp01_rednat: "{{ 'Ingrese2222' not in response_rednatRHP01.content }}"
    
    - name: Hacer una solicitud HTTP a la segunda URL Portal en 146
      uri:
        url: http://172.16.200.146:8080/rrhh/ingreso
        return_content: yes
      register: response_portalRHP02

    - name: Comprobar si el texto 'Empresa222' esta presente en la segunda URL
      set_fact:
        should_act_on_rhp02: "{{ 'Empresa222' not in response_portalRHP02.content }}"

    - name: Hacer una solicitud HTTP a la segunda URL RedNat en 146
      uri:
        url: http://172.16.200.146:8080/grh-nat-web/login.seam
        return_content: yes
      register: response_rednatRHP02

    - name: Comprobar si el texto 'Ingrese2222' esta presente en la segunda URL
      set_fact:
        should_act_on_rhp02_rednat: "{{ 'Ingrese2222' not in response_rednatRHP02.content }}"

    - name: Hacer una solicitud HTTP a la tercera URL Portal balanceador inteno
      uri:
        url: http://172.16.215.2/rrhh/ingreso
        return_content: yes
      register: response_portalRHP02_vm

    - name: Comprobar si el texto 'Empresa222' esta presente en la tercera URL
      set_fact:
        should_check_vm_rhp02: "{{ 'Empresa222' not in response_portalRHP02_vm.content }}"

    - name: Hacer una solicitud HTTP a la tercera URL rednat balanceador inteno
      uri:
        url: http://172.16.215.2/grh-nat-web/login.seam
        return_content: yes
      register: response_rednatRHP02_vm

    - name: Comprobar si el texto 'Ingrese2222' esta presente en la tercera URL
      set_fact:
        should_check_vm_rhp02_rednat: "{{ 'Ingrese222' not in response_rednatRHP02_vm.content }}"

    - name: Hacer una solicitud HTTP a la cuarta URL Portal balanceador externo
      uri:
        url: http://190.210.169.34/rrhh/ingreso
        return_content: yes
      register: response_portalRHP01_vm

    - name: Comprobar si el texto 'Empresa222' esta presente en la cuarta URL
      set_fact:
        should_check_vm_rhp01: "{{ 'Empresa222' not in response_portalRHP01_vm.content }}"

    - name: Hacer una solicitud HTTP a la cuarta URL Portal balanceador externo
      uri:
        url: http://190.210.169.34/grh-nat-web/login.seam
        return_content: yes
      register: response_rednatRHP01_vm

    - name: Comprobar si el texto 'Ingrese222' esta presente en la cuarta URL
      set_fact:
        should_check_vm_rhp01_rednat: "{{ 'Ingrese222' not in response_rednatRHP01_vm.content }}"

- name: Realizar acciones en RHP01 si es necesario
  hosts: 172.16.200.145

  tasks:
    - name: Obteniendo system uptime en RHP01
      command: awk '{print $1}' /proc/uptime
      register: uptime_output
      when: hostvars['localhost'].should_act_on_rhp01 or hostvars['localhost'].should_act_on_rhp01_rednat

    - name: Calcular uptime en minutos en RHP01
      set_fact:
        uptime_minutes: "{{ uptime_output.stdout | float / 60 }}"
      when: hostvars['localhost'].should_act_on_rhp01 or hostvars['localhost'].should_act_on_rhp01_rednat

    - name: Debug uptime minutos en RHP01
      debug:
        msg: "Uptime en minutes: {{ uptime_minutes }}"

    - name: Verificar si se cumple con el minimo tiempo para correr las tareas en RHP01
      debug:
        msg: "Las tareas pueden correr porque tiene mas de 25 minutos iniciado"
      when: uptime_minutes | float >= 25

    - name: Crear log si falta el texto en la primera URL Portal en RHP01
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') El texto 'Empresa222' no se encontro en la URL http://172.16.200.145:8080/rrhh/ingreso" >> /tmp/$(date '+%Y-%m-%d')FallaPortal.log
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_act_on_rhp01

    - name: Crear log si falta el texto en la primera URL Rednat en RHP01
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') El texto 'Ingrese222' no se encontro en la URL http://172.16.200.145:8080/grh-nat-web/login.seam" >> /tmp/$(date '+%Y-%m-%d')FallaRednat.log
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_act_on_rhp01_rednat

    - name: Verificar el estado de la VM vrhp01 si falta el texto en la cuarta URL Portal
      virt:
        command: status
        name: vrhp01
      register: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp01

    - name: Verificar el estado de la VM vrhp01 si falta el texto en la cuarta URL Rednat
      virt:
        command: status
        name: vrhp01
      register: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp01_rednat

    - name: Mostrar el estado de la VM vrhp01 portal
      debug:
        var: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp01

    - name: Mostrar el estado de la VM vrhp01 rednat
      debug:
        var: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp01_rednat

- name: Realizar acciones en RHP02 si es necesario
  hosts: 172.16.200.146

  tasks:
    - name: Obteniendo system uptime en RHP02
      command: awk '{print $1}' /proc/uptime
      register: uptime_output
      when: hostvars['localhost'].should_act_on_rhp02 or hostvars['localhost'].should_act_on_rhp02_rednat

    - name: Calcular uptime en minutos en RHP02
      set_fact:
        uptime_minutes: "{{ uptime_output.stdout | float / 60 }}"
      when: hostvars['localhost'].should_act_on_rhp02 or hostvars['localhost'].should_act_on_rhp02_rednat

    - name: Debug uptime minutos en RHP02
      debug:
        msg: "Uptime en minutes: {{ uptime_minutes }}"

    - name: Verificar si se cumple con el minimo tiempo para correr las tareas en RHP02
      debug:
        msg: "Las tareas pueden correr porque tiene mas de 25 minutos iniciado"
      when: uptime_minutes | float >= 25

    - name: Crear log si falta el texto en la primera URL Portal en RHP02
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') El texto 'Empresa222' no se encontro en la URL http://172.16.200.146:8080/rrhh/ingreso" >> /tmp/$(date '+%Y-%m-%d')FallaPortal.log
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_act_on_rhp02

    - name: Crear log si falta el texto en la primera URL Rednat en RHP02
      shell: echo "$(date '+%Y-%m-%d %H:%M:%S') El texto 'Ingrese222' no se encontro en la URL http://172.16.200.146:8080/grh-nat-web/login.seam" >> /tmp/$(date '+%Y-%m-%d')FallaRednat.log
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_act_on_rhp02_rednat

    - name: Verificar el estado de la VM vrhp02 si falta el texto en la tercera URL Porta
      virt:
        command: status
        name: vrhp02
      register: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp02

    - name: Verificar el estado de la VM vrhp02 si falta el texto en la tercera URL Rednat
      virt:
        command: status
        name: vrhp02
      register: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp02_rednat

    - name: Mostrar el estado de la VM vrhp02 Portal
      debug:
        var: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp02

    - name: Mostrar el estado de la VM vrhp02 Rednat
      debug:
        var: vm_status
      when: uptime_minutes | float >= 25 and hostvars['localhost'].should_check_vm_rhp02_rednat
